# Generated by Django 4.2 on 2023-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_remove_postdetails_name_postdetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='user_image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
